### ISSUE TITLE
Site does not reflect source

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser-website#14]
I updated the versions - how do I publish?

**Comment by ftomassetti** [comment]
It should be automatic... let's see if there are errors or logs

**Comment by ftomassetti** [comment]
Netlify (the service hosting the website) reports that the website was updated 13 hours ago, so it seems the build ran, however the website is not updated. No idea why...

**Comment by ftomassetti** [comment]
I triggered a manual deploy and the site seems to have been updated. If you want I can add you as an administrator to netlify.

**Comment by matozoid** [comment]
Please do add me :-)

**Comment by ftomassetti** [comment]
Invite sent, let me know if you receive it or if you want me to send it to another email

**Comment by matozoid** [comment]
It worked :)
