### ISSUE TITLE
https://javaparser.org presents an invalid certificate

### ISSUE THREAD

**Issue by eager** [javaparser/javaparser-website#22]
<img width="1051" alt="Screen Shot 2019-03-20 at 2 17 04 PM" src="https://user-images.githubusercontent.com/4656/54712662-dd90d480-4b1a-11e9-8bb4-912c405d57e4.png">

https://javaparser.org

**Comment by matozoid** [comment]
@ftomassetti ?

**Comment by ftomassetti** [comment]
We just changed hosting, maybe it is related

**Comment by ftomassetti** [comment]
Hopefully solved

**Comment by matozoid** [comment]
To me it looks fine. @eager?

**Comment by eager** [comment]
@matozoid @ftomassetti certificate looks good 👍 . The homepage still isn’t marked as secure, because of mixed content:

> Mixed Content: The page at 'https://javaparser.org/' was loaded over HTTPS, but requested an insecure image 'http://javaparser.org/wp-content/uploads/2018/02/javaparser-book.jpg'. This content should also be served over HTTPS.

But that’s a silent warning, not the blocking error of an invalid certificate.
